import { useEffect, useState } from "react";
import { useAlert } from "react-alert";
import { Link, useNavigate } from "react-router-dom";
import { useLoginUserMutation } from "../Redux/User";
import { setUser } from "../Redux/UserSlice";
import { useDispatch } from "react-redux";
import { ToastContainer, toast } from "react-toastify";
import { HiOutlineMail } from "react-icons/hi";
import { TbPasswordFingerprint } from "react-icons/tb";

const Login = () => {
  const alert = useAlert();
  const navigate = useNavigate();
  const dispatch = useDispatch();
  const [form, setForm] = useState({
    email: "",
    password: "",
  });

  // Mutation hook generated by RTK Query
  const [loginUser, { isLoading, isError, error }] = useLoginUserMutation();

  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm({ ...form, [name]: value });
  };

  useEffect(() => {
    if (isError) {
      toast.error(error.data.err);
    }
  }, [isError, alert, error]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    // Call the registerUser mutation with form data
    const data = await loginUser(form).unwrap();
    dispatch(setUser(data.user));

    // Registration successful, navigate to login page
    toast.success("Login successful");
    navigate("/");
  };

  return (
    <>
      <div className="max-w-[70%] w-full mx-auto flex items-center justify-center flex-col gap-4 mt-24">
        <form
          onSubmit={handleSubmit}
          action="
        "
          className="flex items-center justify-center flex-col gap-4 border border-slate-300 py-10 px-10 rounded-lg"
        >
          <h1 className="text-3xl font-semibold text-slate-700">Login</h1>

          <div className="border border-slate-300 rounded-md">
            <div className="flex items-center justify-center bg-white p-2 rounded-md">
              <input
                onChange={handleChange}
                required
                name="email"
                type="email "
                placeholder="Enter your email"
                className="outline-none border-none"
              />
              <span>
                <HiOutlineMail className="text-xl text-gray-600" />
              </span>
            </div>
          </div>
          <div className="border border-slate-300 rounded-md">
            <div className="flex items-center justify-center bg-white p-2 rounded-md">
              <input
                onChange={handleChange}
                required
                name="password"
                type="password "
                placeholder="Enter your password"
                className="outline-none border-none"
              />
              <span>
                <TbPasswordFingerprint className="text-xl text-gray-600" />
              </span>
            </div>
          </div>
          <button
            disabled={isLoading}
            type="submit"
            className="w-full tracking-wide font-semibold bg-black text-white py-2 px-2 rounded-md hover:cursor-pointer hover:opacity-80 transition-all duration-200"
          >
            {isLoading ? "Logging in..." : "Login"}
          </button>

          <p>
            Not a user yet ?{" "}
            <span className="text-sm font-semibold">
              <Link to={"/register"} className="text-blue-500">
                Register
              </Link>
            </span>{" "}
          </p>
        </form>
      </div>
      <ToastContainer />
    </>
  );
};

export default Login;
